### ISSUE TITLE
I like it, but...

### ISSUE THREAD

**Issue by AlbertoVelazquez** [XmYx/ainodes-engine#10]
I see that this frontend has a lot of movement and the developer seems interested in people trying it. But I see it very complicated because of the usability of the program.

- Nowhere is it explained how it works. There is no wiki, not even an example project at hand, or I have not come across it. What is the order of the nodes, how to set up a simple image generation?
- Even if it is nodal, it is not different from other programs. If it is nodal but you can't even blur the images, you can't do a face restoration and blur it...

I mean, actually the fact that the program is nodal only leads to a messy interface. I'm very attracted to the project but it needs a better UX and a clearer objective than "it does the same as others but in nodes".

**Comment by AlbertoVelazquez** [comment]
Ah, sorry, I thought that have more time because I confuse with comfyUI. So I supposed that have more time of development. My fault.

**Comment by XmYx** [comment]
No worries at all, all insight help to see how it is perceived You all out there. I did add a Help text to the nodes, I'll fill those as I go with more information.
