### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Vendaciousness** [XmYx/ainodes-engine#19]
Looks like a very interesting and promising project! 

Here's a few things I'd like to see (as a technical artist), so that I can begin using this to make animations:

- A Basic Working Graph, with all the nodes necessary to run an animation, kind of like the basic settings that are automatically loaded with the Auto1111 WebUI version of Deforum. This will give users a place to work from.  As things are, with no documentation and no examples, I'm not sure where to begin and indeed have no way of knowing if there is a setup that will function and create an animation at this time. I know it's super early to ask for this, but you have a public download, so I'm assuming there's a way to get output, so including a basic graph that works and loads when you start the program would be great. 

- A settings feature, where you can specify locations of the various models/checkpoints. I edited the yaml file in the config directory to try to specify some of the file locations, but not all of them were there and when I tried to use the File>Models Dir, none of my changes took, because it opened the same directories as before, even when I tried several kinds of formatting, such as G://models//checkpoint, etc. I have 100GB of models in my SD directories, so I probably have all the files required, but I'd rather not move every kind of file over or set up Symlinks every time I wish to use the software. Maybe have the program automatically download all the smaller files might be easier than hoping users will know where to find these things and where to put them all.

- Ability to make networks you can go inside, like in TouchDesigner would be very cool. Obviously, basic functionality is more important, but just making an observation, with the amount of settings required to make Deforum work, it would be nice if you could hide the settings that weren't being changed, perhaps in this way.  Speaking of TouchDesigner, there are a number of projects that use TD to control SD and you might want to check them out for ideas, because there's no point in re-inventing the wheel.

- Sometimes, the panning function (middle mouse button) stopped working until I zoomed in/out.

I'm okay with experimenting and trial and error, but only if I know there's a way to make it work.  If the software works, but needs users to request stuff and find bugs, no problem.  But if you want people to put time and effort into the repo, the burden is on you to first provide settings files or instructions we can follow to get some kind of functionality, so we know we're not wasting our time setting up something that's not going to work.

Bear in mind, I'm just technical artist, so my views may not reflect those of your ideal users.  I hope something here is useful to you and I wish you luck on your project!

I look forward to seeing this repo become the ultimate node-based animation software!  Keep up the good work!

**Comment by XmYx** [comment]
Hi!

Thank you for reaching out, and sharing your insights, they are really useful, and follow my thinking as well. To address those:

You'll find example graphs in the file menu - Example Graphs - ainodes_engine_deforum_nodes - deforum.json is the one as a Deforum template (WIP).

Settings editor window coming up, the system does use a config in the main config folder.

Subgraphs are implemented, and you'll find them on the left, at Subgraph Nodes (to build them) and Subgraphs (to quickly reuse them)

Panning is buggy. :D

I'll make sure to update this thread about the remaining issues! : )

**Comment by XmYx** [comment]
I will close this issue as panning was somewhat addressed, and further fixes regarding panning will be tracked in:
[https://github.com/XmYx/ainodes-engine/issues/22](url)

I will make sure to add the settings feature to the tracking list found in the mentioned issue.
