### ISSUE TITLE
fails to start after following instructions for windows

### ISSUE THREAD

**Issue by nicholasVANDAL** [XmYx/ainodes-engine#23]
I have followed the instructions for installing on windows.
I have python 3.10, nvidia drivers with CUDA, and GIT.
I have downloaded the 1 click installer and run it.
I have the shortcut generated on my desktop.
I double click it, console pops up and closes straight away.

I am on windows 11.

and I am now sad

**Comment by nicholasVANDAL** [comment]
when running main.py directly i get this

c:\...\ainodes-engine>python main.py
Traceback (most recent call last):
  File "C:\...\ainodes-engine\main.py", line 5, in <module>
    from PyQt6.QtCore import QPropertyAnimation, QEasingCurve
ModuleNotFoundError: No module named 'PyQt6'

**Comment by XmYx** [comment]
hey, the error message suggests that you are missing the requirements for the iterator nodes package by osi
please, while in the venv, go through each folder in the custom_nodes folder, and make sure to do a git pull, and pip install -r requirements.txt, as well as in the main repo (ainodes-engine)

**Comment by XmYx** [comment]
I think we have talked on Discord, and your installation worked afterall, so closing this issue. Please make sure to reach out on Deforum discord if you are facing any install issues.
