### ISSUE TITLE
Errors after installing on Linux

### ISSUE THREAD

**Issue by tkocou** [XmYx/ainodes-engine#25]
I followed the instructions for installing in Linux. The first error was: 

Package gobject-introspection-1.0 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'gobject-introspection-1.0' found
      Command '('pkg-config', '--print-errors', '--exists', 'gobject-introspection-1.0 >= 1.56.0')' returned non-zero exit status 1.
      
      Try installing it with: 'sudo apt install libgirepository1.0-dev'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pygobject
Failed to build pygobject
ERROR: Could not build wheels for pygobject, which is required to install pyproject.toml-based projects

So I installed the libgirepository1.0-dev package.  Now the program throws this error:

PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
Using HF Cache in app dir
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: vkkhrdisplay, wayland, eglfs, minimal, wayland-egl, offscreen, xcb, vnc, linuxfb, minimalegl.

Aborted (core dumped)

I have GTK 3 installed. Is there some other library missing?

**Comment by XmYx** [comment]
Hi! What linux distro did you try?
Normally you should be able to run it if you have pyqt6 installed, and are able to run other Qt based applications.
If you are running in a docker, then you'll probably need to make sure that your display is attached to the docker instance, and that you have exposed your xhost, i think its either "host+" or "xhost+". Above that there are a couple of docker images made to demonstrate running gui apps in it.
If not in docker, you should be fine with just a virtualenv, or venv, even conda.

**Comment by tkocou** [comment]
Thank you for the reply. I'll check on the pyqt6 installation.
