### ISSUE TITLE
Windows one click installer problem

### ISSUE THREAD

**Issue by SoftologyPro** [XmYx/ainodes-engine#31]
The one click installer batch runs, shows "AiNodes - Engine installation complete, starting.", shows the splash screen for a split second and that's all.

Double-clicking the desktop icon does the same.

Running from a command line ends with
    import psutil
ModuleNotFoundError: No module named 'psutil'

Also, at the end of the install the screen is cleared which stops anyone scrolling up to see any stats and potential causes of the problem, so I do not have any log to share.  That screen clear should be removed.  Line 144 of setup_ainodes.bat

**Comment by Sam-Rowe** [comment]
I am having the same issue. 

I have added psutil to the requirements.txt file and started the app by hand with run_ainodes.bat instead but it then is missing another package  'omegaconf'

Is this a Windows only thing?

If I get it working I may put in a PR and let someone on Linux/Mac give it a test to prove if I am out on a ledge here.

**Comment by Sam-Rowe** [comment]
Looking into it, there is another issue open that has some info on a workaround. Investigating that in issue #27

**Comment by XmYx** [comment]
> Looking into it, there is another issue open that has some info on a workaround. Investigating that in issue #27

Hi! Thanks a lot for looking into it, if you maybe want to jump on Deforum discord, we could share a little quicker, although generally speaking, the steps to fix the issue will surely consist of updating the comfy handling logic, and updating requirements in general of course. I will soon be replacing the deforum module currently being used, and doing a general clean-up / update to make the app start up quicker and to be less prone to errors. Actually, just the past few days I was considering removing the auto-run logic completely when solving the graphs and go back to only doing the Unreal type execution logic, adding variables in the picture for a bit of confusion and flexibility. Anyhow, I'll soon also push a new branch. : ))

**Comment by XmYx** [comment]
The issue has been solved - a long ago - sorry to have left the issue stale here.
