### ISSUE TITLE
ControlNet Loader model selection box is too short.

### ISSUE THREAD

**Issue by popedead** [XmYx/ainodes-engine#7]
ControlNet Loader model selection box is too short, I organized my model names with slightly longer names, but the box is too short and summarizes them and they all look the same, the node seems to support a bigger box, tanx, win10, 3080 ti, fullhd screen

**Comment by XmYx** [comment]
Added mechanic to check text length, going to make it inherited for the rest of the dropdowns too, also have to handle resizing inheritively a bit better.

**Comment by popedead** [comment]
![controlne](https://user-images.githubusercontent.com/19626939/226111033-80a0ecc0-96fd-4249-9bd0-f875d5b09cee.png)
pareciera no haber cambio

**Comment by XmYx** [comment]
Added logic to auto resize dropdown after selection.
