### ISSUE TITLE
drag and drop image to input?

### ISSUE THREAD

**Issue by popedead** [XmYx/ainodes-engine#8]
drag and drop image to input? Would it be possible? Now with the net control models one places many control images in the interface and it becomes very slow to have to go looking for them one by one, and even more so if one tries many, if possible it would be good to drag directly to the node input to change the image and also drag and an input node is created with the image, so one can make different combinations in a fluid way, thanks, win 10 3080ti.

**Comment by XmYx** [comment]
Possible, I'll check how to properly catch the event in case it is not from a path, but an object from somewhere. Till then, I'll add a List node, where you can open a folder of images, have them in a list, and choose what goes out.
