### ISSUE TITLE
prompt in conditioning node is a illegible

### ISSUE THREAD

**Issue by popedead** [XmYx/ainodes-engine#9]
in the conditioning node the color of the background is white and that of the text is a very light gray, it can only be read by selecting it, windows 10, 3080ti, fullhd screen

**Comment by popedead** [comment]
example
![prompt](https://user-images.githubusercontent.com/19626939/226111096-8b623e02-30fc-44d0-9d1d-01d57b2b1bdd.png)

**Comment by XmYx** [comment]
Fixed now on both OS's.
